### ISSUE TITLE
suggestion: consider renaming few things for readibility

### ISSUE THREAD

**Issue by alaypatel07** [automationbroker/bundle-lib#104]
The function [ConvertBuncleToSpec](https://github.com/automationbroker/bundle-lib/blob/84c06b4bb09011ce638980f8365325b5d4ace1bd/crd/conversions.go#L39) takes input parameter spec, which should be renamed to bundleSpec.

This file [conversions.go](https://github.com/automationbroker/bundle-lib/blob/master/crd/conversions.go#L39) has functions that says "convert_ToAPB" that should be renamed to "convert_ToSpec_"

**Comment by jmrodri** [comment]
I do not think we should rename the input parameter. The type is of `bundle.Spec` that should identify what it is, bundleSpec is just superfluous.

Right now the convert_ToAPB while it isn't correct with today's terminology, it is consistent with all the other calls. I vote to leave it alone, just a historical wart as the code has progressed.
