### ISSUE TITLE
suggestion: move to using pkg errors and remove error logging

### ISSUE THREAD

**Issue by maleck13** [automationbroker/bundle-lib#106]
In many places in bundle-lib we follow an error pattern that looks like this:

``` 
if err != nil{
    log.Error("failed to load images from registry")
    return err
}
```
While there is nothing really wrong with this, it ends up with multiple logs happening as the caller will also log the err. It is also possible to lose the valuable context that is logged before returning the error.

If we use the https://github.com/pkg/errors then we change the above to be

```
if err != nil{
    return errors.Wrap(err, "failed to load images from registry")
}
```

This keeps the context as now when the consumer of the lib logs the error they would see something like:

```
"some network err : failed to load images from registry"
```

Also if they log with a format of ```%+v``` they will get a stack trace

**Comment by maleck13** [comment]
As mentioned by @shawn-hurley, this really is about the UX of the lib and how we want error handling to work. Not a priority issue.
An example of this is when we handle errors just by logging them. We could instead return a multi error.

Generally I am in favor of handling errors by adding context to the error and handing it back up the stack to the caller. This way full control is in the hands of the lib consumer. There may be some exceptions to this of course

**Comment by maleck13** [comment]
possibly related https://github.com/automationbroker/bundle-lib/issues/94

**Comment by shawn-hurley** [comment]
@maleck13 So I was just thinking more about this, and I don't disagree with you that we need to handle the errors better but I want to add a second idea to the mix just to see what people think.

I wonder if having defined errors for the entire api surface might be a better user experience. This will allow bundle lib to change implementation details underneath the hood and still have stable error api that a user can relay on. This also might be pre mature optimization.

**Comment by jmrodri** [comment]
Closing stale issues
