### ISSUE TITLE
Bundle Package should have a sub package for errors 

### ISSUE THREAD

**Issue by shawn-hurley** [automationbroker/bundle-lib#111]
carried over from https://github.com/openshift/ansible-service-broker/issues/782 

I think that we should consider this in conjunction or as a part of https://github.com/automationbroker/bundle-lib/issues/106 but just adding issue to keep track.

**Comment by shawn-hurley** [comment]
I don't think this is a priority and we should not consider this critical. 

The idea of this is to create an API for the errors. This will allow for us to add more context into the errors, allow users to depend on certain type of errors to handle them correctly and allow us to control the output of bundle-lib. I personally don't see a need at the moment for this @jmrodri @dymurray from either the broker or CLI perspective is this something that should be prioritized?

**Comment by jmrodri** [comment]
Closing stale issues
