### ISSUE TITLE
Remove Origin Copy from Bundle Lib

### ISSUE THREAD

**Issue by djzager** [automationbroker/bundle-lib#12]
Checklist:

- [x] Move the copy of origin back to the `ansible-service-broker` project
- [x] Update internal openshift client to use actual openshift clients and APIs
- [x] Write conversion step into verify identity in handler/handler.go
- [x] Update `local_openshift` to use openshift clients and APIs

**Comment by shawn-hurley** [comment]
All ASB changes will have to wait till the master branch re-opens up.

**Comment by shawn-hurley** [comment]
Closed once https://github.com/openshift/ansible-service-broker/pull/946 is merged
