### ISSUE TITLE
bundle.Spec needs a mark for deletion field

### ISSUE THREAD

**Issue by alaypatel07** [automationbroker/bundle-lib#120]
With the approach for reconciliation decided [here](https://www.redhat.com/archives/ansible-service-broker/2018-July/msg00003.html), the bundle.Spec struct needs to have a **mark for deletion** field.

**Comment by jmrodri** [comment]
@shawn-hurley mentioned kubernetes objects already have this field in the ObjectMeta
https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta
