### ISSUE TITLE
Do we want a Makefile here?

### ISSUE THREAD

**Issue by eriknelson** [automationbroker/bundle-lib#14]
Could use it for make test or future uses.

**Comment by eriknelson** [comment]
Probably also for check and ci? (lint, vet, ci etc.)

**Comment by shawn-hurley** [comment]
#16 is also probably either directly tied to this or dependent on a make file?

**Comment by eriknelson** [comment]
It's all related. I don't care if it's a makefile, but we have to have a `check` and `ci` a dev can run from their machine before they submit. Makefiles are normally how we do that.

**Comment by jmrodri** [comment]
I say we steal the broker one and then rip out what we don't need. That's what I did with the osb-broker-lib projects.

**Comment by eriknelson** [comment]
+1, that's what I was thinking @jmrodri
