### ISSUE TITLE
Need to create a Travis CI job for the library

### ISSUE THREAD

**Issue by shawn-hurley** [automationbroker/bundle-lib#16]
This should run the testes, should report test coverage, and should make sure that it builds.

I wonder if also we need to have a reference implementation of the project in a `example` folder?

**Comment by eriknelson** [comment]
> I wonder if also we need to have a reference implementation of the project in a `example` folder? 

I would really like to see this. I have a horrible project for working with these libs in practice. I'll spare my disparaging go comments.

**Comment by shawn-hurley** [comment]
closed by #28
