### ISSUE TITLE
Respect additional authorization token field

### ISSUE THREAD

**Issue by sjahreis** [automationbroker/bundle-lib#174]
Docker specifies the following `token` headers during registry authorization:
- `token`: An opaque Bearer token that clients should supply to subsequent requests in the Authorization header.
- `access_token`: For compatibility with OAuth 2.0, we will also accept token under the name access_token. At least one of these fields must be specified, but both may also appear (for compatibility with older clients). When both are specified, they should be equivalent; if they differ the client's choice is undefined.

See https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md#token-response-fields for more details.

The `bundle-lib` only accepts the `access_token` field. See https://github.com/automationbroker/bundle-lib/blob/master/registries/adapters/oauth/client.go#L35-L37 and https://github.com/automationbroker/bundle-lib/blob/master/registries/adapters/oauth/client.go#L191 for more details. 

But registries like Artifactory or Harbor send their token in the field `token`. Therewith we couldn't connect them with the Automation Broker.

I'll create a  PR which respects the additional token field `token` as well.

**Comment by eriknelson** [comment]
@sjahreis Once this PR merges (https://github.com/openshift/ansible-service-broker/pull/1167), CI should build and publish you a new image at `docker.io/ansibleplaybookbundle/origin-ansible-service-broker:canary`, you can check the status of that here https://hub.docker.com/r/ansibleplaybookbundle/origin-ansible-service-broker/tags.

**Comment by sjahreis** [comment]
@eriknelson: Thanks! :-)
