### ISSUE TITLE
Connecting with Artifactory / Harbor Docker registries

### ISSUE THREAD

**Issue by sjahreis** [automationbroker/bundle-lib#176]
Hey guys,

we are currently experimenting with the Automation Broker and having several issues in conjunction with Artifactory and/or Harbor.

- We tried to use the [API V2 Registry Adapter](https://github.com/openshift/ansible-service-broker/blob/master/docs/config.md#api-v2-registry) but ran into the following Issue https://github.com/automationbroker/bundle-lib/issues/174

- Using our contributed fix we are able to obtain a token now, but run into more issues:
  - Artifactory returns an EOF
  - Harbor returns an 401 Unauthorized

---
## Assumptions:

Currently the OAuth Client performs the following flow:
1. GET https://demo.goharbor.io/v2/ -> Www-Authenticate `realm` & `service`
2. GET `realm`?service=`service` including BasicAuth -> `token`
3. GET https://demo.goharbor.io/v2/_catalog including `token` -> list images

---
## Questions/Problems:

- **Harbor**: In step 3 Harbor returns a 401 Unauthorized answer with the following content:
```json
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "authentication required",
            "detail": [
                {
                    "Type": "registry",
                    "Class": "",
                    "Name": "catalog",
                    "Action": "*"
                }
            ]
        }
    ]
}
```

The response shows the required scope which has to be contained in the token.

Instead of https://demo.goharbor.io/v2/ shouldn't the first request be sent to https://demo.goharbor.io/v2/_catalog? This way the response would contain the required `scope` (next to `realm` and `service`) which is also specified in Docker's Token Authentication Specification (see https://docs.docker.com/registry/spec/auth/token/#requesting-a-token).

```json
www-authenticate: Bearer realm="https://demo.goharbor.io/service/token",service="harbor-registry",scope="registry:catalog:*
```

The value of `scope` could be sent as parameter in request 2. This way the resulting `token` contains the correct scope.

- **Artifactory**: Artifactory returns an EOF when we request the catalog endpoint. The reason for the EOF is, that Artifactory exposes a separate catalog endpoint for every of it's repositories (e.g. https://demo.artifactory.io/v2/myregistry/_catalog). So do we need a separate Adapter for Artifactory?

**Comment by jmrodri** [comment]
Closing stale issues
