### ISSUE TITLE
Clients kubernetes function requires a  .kube config

### ISSUE THREAD

**Issue by shawn-hurley** [automationbroker/bundle-lib#30]
I don't that we should require anything here. 

I don't have an idea on how to fix ATM.

**Comment by maleck13** [comment]
One option here is to accept the client interface type as part of the constructor. This is generally how go does dependency injection, which I think makes a lot of sense here. We would maintain the central place to get and configure the client but accept the mockable interface in the constructor.
This would allow us to use the fake clients without requiring a user to have a valid .kube config set up

```go 

func NewStateManager(k8sClient kubernetes.Interface) *StateManager{
    return &StateManager{
                   client: k8sClient,
               }
}

func (sm *StateManager)DoSomething()error{
     sm.client.CoreV1().Configmaps("namespace")....

}

```
