### ISSUE TITLE
Bundle Lib needs to expose an option to deploy the APB in the same namespace as the target namespace

### ISSUE THREAD

**Issue by shawn-hurley** [automationbroker/bundle-lib#51]
## Feature

The bundle lib at times will need to deploy the apb into the same namespace as the target of the apb. 

## Current Behavior

There is no way to currently tell bundle-lib to not create the transient namespace.

**Comment by shawn-hurley** [comment]
### Proposal

I think that we should expose an option on the Executor. I think that we should think about this as a per apb run feature and not a runtime configuration option.

### Benifits

I think that the creation of an executor configuration is a pattern that we have established in bundle-lib. I think that we have multiple things that should be added to this in the future. I.E system-level parameters or a request id to unify the logging. 

#### Changes
- [x] create an `ExecutorConfiguration`
- [x] add param to NewExecutor to take the ExecutorConfiguration
- [x] default behavior would be to create the transient namespace
- [ ] break out creation of namespace to runtime package
- [ ] add check before running creation of namespace
- [ ] add check in `CreateSandbox` to see if we need to add rolebinding for the target namespace.

**Comment by shawn-hurley** [comment]
@eriknelson @jmrodri @rthallisey @dymurray ^ can you guys validate that the above makes sense?

**Comment by jmrodri** [comment]
How do I trigger this behavior? Parameter in the APB?

**Comment by shawn-hurley** [comment]
This would be a configuration option for when you create the executor. Thes option would be triggered by running `executuor.Provision(....)` or some other action on the executor.

**Comment by rthallisey** [comment]
@shawn-hurley so this would be a custom override for executor, but when do you know to use one or the other? I guess this is the same as @jmrodri 's question.

**Comment by shawn-hurley** [comment]
I think that it is actually the developer who has vendored bundle lib makes that decision. 

If you asking how the ASB would use this feature I don't think that it would.

**Comment by rthallisey** [comment]
ack from me @shawn-hurley

**Comment by rthallisey** [comment]
maybe we can have a different broker image that uses this path? ansible-service-broker-dev?

**Comment by shawn-hurley** [comment]
I don't see a reason that the ASB would ever need this feature. This feature is for something like the bundlecltr for lostromos, which requires that the operator interacts with just a single namespace.

Why do we need to make a new image of the broker?

**Comment by rthallisey** [comment]
Just a thought on how the broker could include any custom plugins.  This one could be interesting for folks doing development work to aid debugging.

**Comment by shawn-hurley** [comment]
An example of where this is need is in lostromos. ALM deploys an operator(lostromos) that only has access to a single namespace (the target namespace), and the operator(lostromos) vendors this library. We should be able to launch APBs in the target namespace and have them manage the target namespace. Currently, there is not way to do this.
