### ISSUE TITLE
add errcheck as part of the make check command

### ISSUE THREAD

**Issue by maleck13** [automationbroker/bundle-lib#89]
Sometimes it is possible to miss handling an error. Rather than relying on review to catch this we could include the popular errcheck tool as part of the ```make check``` command.

https://github.com/kisielk/errcheck

Happy to take this on if we want to do it

**Comment by eriknelson** [comment]
+1, this sounds useful!

**Comment by jmrodri** [comment]
We decided against implementing this

> After some thought I don't think this should be merged. Wrapping the `Close()` in a function simply to log the error to satisfy the tool smells, since we are not actually "handling" the error. 
>
> Also, having the errcheck tool doesn't really force me to handle the error other than possibly logging it which isn't really handling it.
>
> And finally I would like to be able to ignore errors, sometimes I just don't care. resp.Body.Close() is precisely one of those situations where I don't care.
>
> I brought this up with @eriknelson and @shawn-hurley, so we're going to close this PR.
