### ISSUE TITLE
suggestion: move away from panic in the lib

### ISSUE THREAD

**Issue by maleck13** [automationbroker/bundle-lib#94]
Generally I don't think it is good practice to panic in a library. Doing this assumes a number of things about the caller of the library:

- They have a panic handler 
- OR they want their application to crash if this lib doesn't work 

I am not sure we should make these assumptions. In a situation where an error occurs I believe the lib should hand back control to the caller and allow it to decide what to do in that situation as the caller has the full context and domain knowledge.

**Comment by jmrodri** [comment]
```
$ git grep "panic(" | grep -v test
clients/crd.go:			panic(err.Error())
clients/etcd.go:			panic(err.Error())
clients/kubernetes.go:			panic(err.Error())
clients/kubernetes.go:		panic(err.Error())
clients/openshift.go:			panic(err.Error())
runtime/runtime.go:		panic(err.Error())
runtime/runtime.go:			panic(err.Error())
runtime/runtime.go:		panic(err.Error())
runtime/runtime.go:			panic(fmt.Errorf("Broker is attempting to delete its own namespace"))
```

**Comment by jmrodri** [comment]
IRC meeting this morning the recover docs were referenced:
https://blog.golang.org/defer-panic-and-recover

Particularly these two sections:

> Recover is a built-in function that regains control of a panicking goroutine. Recover is only useful inside deferred functions. During normal execution, a call to recover will return nil and have no other effect. If the current goroutine is panicking, a call to recover will capture the value given to panic and resume normal execution. 

> For a real-world example of panic and recover, see the [json package](https://golang.org/pkg/encoding/json/) from the Go standard library. It decodes JSON-encoded data with a set of recursive functions. When malformed JSON is encountered, the parser calls panic to unwind the stack to the top-level function call, which recovers from the panic and returns an appropriate error value (see the 'error' and 'unmarshal' methods of the decodeState type in [decode.go](https://golang.org/src/pkg/encoding/json/decode.go)). 

The general consensus is to use a recover paradigm for the panics in the client package. And modify [NewRuntime](https://github.com/automationbroker/bundle-lib/blob/master/runtime/runtime.go#L102-L127) to return errors instead of panicking.

**Comment by jmrodri** [comment]
Closing stale issues
